/**
 * Generate the embedded Source Sans 3 faces from `@fontsource/source-sans-3`.
 *
 * An exported SVG names Source Sans 3 but, on its own, cannot load it: used as
 * an `<img>` or opened as a file it has no network access, so it falls back
 * to the system font. That is worse than a different look — auto-layout is
 * measured in Source Sans 3 (`fontMetrics.generated.ts`), so a fallback face
 * changes every string's width and labels run into their neighbours.
 *
 * So the renderer embeds the faces an illustration uses. These are the
 * fontsource `latin` subsets, the same files Google Fonts serves for Latin
 * text, as base64 woff2. Output is committed like the other generated files,
 * so a build does not need this package; it is how a font update gets in.
 *
 * Source Sans 3 is © Adobe, under the SIL Open Font License 1.1, which
 * permits embedding.
 *
 *   node --experimental-strip-types scripts/build-font.ts
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const PKG = join(ROOT, 'node_modules', '@fontsource', 'source-sans-3');
const WEIGHTS = [400, 600, 700] as const;

const version = JSON.parse(readFileSync(join(PKG, 'package.json'), 'utf8')).version as string;
const faces = WEIGHTS.map((w) => {
  const file = join(PKG, 'files', `source-sans-3-latin-${w}-normal.woff2`);
  return [w, readFileSync(file).toString('base64')] as const;
});

const out = `/**
 * GENERATED by scripts/build-font.ts from @fontsource/source-sans-3@${version}
 * — do not edit. Source Sans 3 latin subset, woff2, base64. © Adobe, SIL OFL 1.1.
 */

export const FONT_FACES: Record<${WEIGHTS.join(' | ')}, string> = {
${faces.map(([w, b64]) => `  ${w}: '${b64}',`).join('\n')}
};
`;
writeFileSync(join(ROOT, 'src', 'font.generated.ts'), out);
console.log(
  `wrote src/font.generated.ts — ${faces.map(([w, b]) => `${w}: ${Math.round(b.length / 1024)} KB`).join(', ')}`,
);
